Add client library and change to monorepo
neodyland/autosharding pull request #1
Opened 2024-07-25 15:08 UTC by tuna2134

2024-07-26 05:37 UTC, tasuren requested changes

2024-07-26 05:37 UTC, tasuren commented on autosharding-client/src/client.rs
> +    pub async fn get_shard_id(&mut self) -> Result<u32> {
`acquire`にすれば。

2024-07-26 08:04 UTC, tuna2134 commented on autosharding-client/src/client.rs
> +    pub async fn get_shard_id(&mut self) -> Result<u32> {
おっけ

2024-07-27 04:13 UTC, tuna2134 commented
修正したよ

2024-07-28 02:12 UTC, tasuren requested changes

2024-07-28 02:12 UTC, tasuren commented on autosharding-client/src/lib.rs
> +pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;
ここはanyhow使わないの？

2024-07-28 02:12 UTC, tasuren commented on autosharding-client/src/client.rs
> +        println!("{}", shard_id);
assertすれば。
例えばシャード獲得を二回行ったら、得られるシャードIDは0と1であるはず。これをassert_eqする。

2024-07-28 02:12 UTC, tasuren commented on autosharding-client/src/client.rs
> +            println!("{}", client.get_shard_id().await.unwrap());
上のコメントと同じく、assertすれば。

2024-07-28 02:12 UTC, tasuren commented on autosharding-client/src/client.rs
> +    }
リリースは後で実装する感じ？

2024-07-28 02:26 UTC, tuna2134 commented on autosharding-client/src/client.rs
> +    }
うん

2024-07-28 02:27 UTC, tuna2134 commented on autosharding-client/src/lib.rs
> +pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;
anyhowをライブラリに使うのは、、、

2024-07-28 02:28 UTC, tuna2134 commented on autosharding-client/src/client.rs
> +            println!("{}", client.get_shard_id().await.unwrap());
いきなり馬鹿でかい数字だったとおもうけど、、、？

2024-07-28 02:28 UTC, tuna2134 commented on autosharding-client/src/client.rs
> +        println!("{}", shard_id);
でかい数字だったけど？

2024-07-28 09:58 UTC, tasuren commented on autosharding-client/src/lib.rs
> +pub type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;
まあでも今の所必要性は感じないから別にいいか。

2024-07-28 10:01 UTC, tasuren commented on autosharding-client/src/client.rs
> +        println!("{}", shard_id);
え、がち？

https://github.com/neodyland/autosharding/blob/98aa1e1b25b06262283bc2294ebc8447590a3934/autosharding-server/src/sys/mod.rs#L27
にあるように0から始まると思うのだけど、どういう数字だった？

2024-07-28 10:25 UTC, tuna2134 commented on autosharding-client/src/client.rs
> +        println!("{}", shard_id);
999から始まってた記憶

2024-07-29 09:06 UTC, tasuren commented on autosharding-client/src/client.rs
> +        println!("{}", shard_id);
わかったわ原因。修正した。

2024-07-29 09:39 UTC, merged